language: node_js
matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      node_js: "4" # to be removed 2018-04-01
    - os: linux
      dist: trusty
      sudo: required
      node_js: "6" # to be removed 2019-04-01
    - os: linux
      dist: trusty
      sudo: required
      node_js: "7" # to be removed 2017-06-30
    - os: linux
      dist: trusty
      sudo: required
      node_js: "8" # to be removed 2020-01-01
    - os: osx
      osx_image: xcode8
      node_js: "8" # to be removed 2020-01-01
addons:
  firefox: latest
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export CHROME_BIN=chromium-browser; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export DISPLAY=:99.0; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sh -e /etc/init.d/xvfb start; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew cask install google-chrome; fi
script:
  - "npm test"
