sudo: required
dist: trusty
language: node_js
node_js:
  - "0.10"
  - "0.12"
  - "4"
  - "5"
  - "6"
addons:
  firefox: latest
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
before_install:
  - "export DISPLAY=:99.0"
  - "export CHROME_BIN=/usr/bin/google-chrome"
  - "sh -e /etc/init.d/xvfb start"
script:
  - "npm test"
